Второй коммит
GUlyanov/java-pro pull request #1
Opened 2024-06-18 07:06 UTC by GUlyanov

Задача1. Реализовать приложение, способное «прогонять тесты».

2024-06-22 14:31 UTC, Alexandr056 requested changes
хорошая работа, но нужны доработки

2024-06-22 14:31 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +        Method beforeTest  = getMethWithAnno(cl, BeforeTest.class, 3);
можете добавить аннотации @BeforeTest и @AfterTest, метод**ы** таких методов может быть несколько

2024-06-22 14:31 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +        Method afterTest  = getMethWithAnno(cl, AfterTest.class, 4);
можете добавить аннотации @BeforeTest и @AfterTest, метод**ы** таких методов может быть несколько

2024-06-22 14:31 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +import static ru.innotech.annotations.Anno.*;
а что за имя класса Anno?

2024-06-22 14:31 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/Anno.java
> +        for (Method mt : methods) {
данный цикл проходится 4 раза для каждой аннотации которую вы ожидаете встретить 1 раз, не оптимально

2024-06-22 14:31 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/Anno.java
> +        return s.substring(s.lastIndexOf(".")+1);
в чем смысл выносить эту строку в отдельный метод?

2024-06-22 14:31 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/Anno.java
> +    // Проверить кол-во объектов в классе
количество ОБъектов в Классе?
Объекты создаются из классов

2024-06-22 14:31 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/Anno.java
> +            Object rez = mt.invoke(obj, pars);
inline variable
return mt.invoke(obj, pars)

2024-06-22 14:31 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/Anno.java
> +            throw new Exception(e.getMessage());
а в чем смысл такой обертки?

2024-06-22 14:31 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/Anno.java
> +    public static List<Method> getTestMethods(Class cl){
отлично

2024-06-22 14:31 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/Anno.java
> +    public static void doBeforeTest(Method annoMt, Method mt, int nTst) throws Exception {
два одинаковых метода

2024-06-23 16:07 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Anno.java
> +    // Проверить кол-во объектов в классе
Александр, тут я не понял вашей мысли. Если в классе организована регистрация инстанционирования объектов или подсчет созданных экземпляров в статическом поле данного класса, то статический метод данного класса может ответить на вопрос, какое количество объектов создано на данный момент в данном классе.  Так что "количество объектов в классе" довольно точно отражает предназначение метода getCount()

2024-06-24 09:06 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +        Method beforeTest  = getMethWithAnno(cl, BeforeTest.class, 3);
исправил

2024-06-24 09:06 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Anno.java
> +        for (Method mt : methods) {
исправил

2024-06-24 09:06 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +import static ru.innotech.annotations.Anno.*;
исправил

2024-06-24 09:06 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +        Method afterTest  = getMethWithAnno(cl, AfterTest.class, 4);
исправил

2024-06-24 09:06 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Anno.java
> +            Object rez = mt.invoke(obj, pars);
исправил

2024-06-24 09:06 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Anno.java
> +            Object rez = mt.invoke(obj, pars);
исправил

2024-06-24 09:07 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Anno.java
> +            throw new Exception(e.getMessage());
исправил

2024-06-24 09:07 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Anno.java
> +    public static List<Method> getTestMethods(Class cl){
исправил

2024-06-24 09:07 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Anno.java
> +    public static void doBeforeTest(Method annoMt, Method mt, int nTst) throws Exception {
исправил

2024-06-24 09:07 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Anno.java
> +    public static void doBeforeTest(Method annoMt, Method mt, int nTst) throws Exception {
Все замечания учтены, изменения внесены. Закомичено и запушено

2024-06-25 02:26 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Anno.java
> +        return s.substring(s.lastIndexOf(".")+1);
исправил

2024-06-26 10:53 UTC, Alexandr056 requested changes
работа содержит много замечаний и функционала который не относится к заданию, прошу провести работу над ошибками и свериться с пунктами задания

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +        Annotation ann;
не стоит так называть переменные + она не используется далее

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +        List<Method> lst;
преждевременная инициализация

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +        Map<String,List<Method>> ans = getMethWithAnno(cl, 1);
название метода снова не отражает суть того что делает, получается по факту возвращает мапу методов сгруппированных по имени аннотации, которой они помечены

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +    public static Map<String,List<Method>> getMethWithAnno(Class cl, int nTst){
зачем тут переменная nTst совершенно не понятно о чем она, и более того она не используется

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +                String key = getLastName(an.annotationType().getName());
мы в чате обсуждали как получать имя аннотации зачем здесь убирать @ и прочее? у вас по прежнему там ссылки?

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +    public static void ValidAnnotations(Map<String,List<Method>> map) throws Exception {
названия методов с маленькой буквы

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +    public static void ValidAnnotations(Map<String,List<Method>> map) throws Exception {
validateAnnotations - скорее

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +    // Проверить кол-во объектов в классе
какие объекты вы проверяете?

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +            int nCount = (int)mt.invoke(null, null);
classCastException возможен

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +            if (nCount != 3) throw new Exception("");
выбрасывать исключение без текста ошибки плохая практика, совсем не понятно будет что случилось

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +            throw new Exception(e.getMessage());
нет тогда смысла перехватывать три вида исключений, просто сразу напишите Exception и все

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/Employee.java
> +    private static List<Employee> emps = new ArrayList<>();
вообще не нужно

2024-06-26 10:53 UTC, Alexandr056 commented on src/main/java/ru/innotech/annotations/Employee.java
> +    private BigDecimal fee;
что такое фее?

2024-06-26 11:07 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +                String key = getLastName(an.annotationType().getName());
Имя аннотации из функции getName() получается некрасивое. @xxx.www.eee.rr.BeforeTest()

2024-06-26 11:08 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +                String key = getLastName(an.annotationType().getName());
Вот и понадобилось преобразование. Кому оно мешает?

2024-06-26 11:11 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Employee.java
> +    private BigDecimal fee;
fee - это оклад работника

2024-06-26 11:15 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +        Annotation ann;
исправил

2024-06-26 11:17 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +        List<Method> lst;
передвинул

2024-06-26 11:21 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestRunner.java
> +        Map<String,List<Method>> ans = getMethWithAnno(cl, 1);
getMethodsByAnnotationMap

2024-06-26 11:22 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +    public static Map<String,List<Method>> getMethWithAnno(Class cl, int nTst){
убрал

2024-06-26 11:34 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +                String key = getLastName(an.annotationType().getName());
Да, действительно @ и () в имени нет. Это я при отладке на ссылку посмотрел. Но имя пакета лучше убрать из имени аннотации. Потом неудобно будет искать по короткому имени полное имя аннотации. Исправил

2024-06-26 11:36 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +    public static void ValidAnnotations(Map<String,List<Method>> map) throws Exception {
исправил

2024-06-26 11:37 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +            int nCount = (int)mt.invoke(null, null);
убрал ненужный метод

2024-06-26 11:39 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +            if (nCount != 3) throw new Exception("");
ненужный метод убрал

2024-06-26 11:39 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +            throw new Exception(e.getMessage());
ненужный метод убрал

2024-06-26 11:43 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Employee.java
> +    private static List<Employee> emps = new ArrayList<>();
убрал

2024-06-26 11:43 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Employee.java
> +    private BigDecimal fee;
то есть жалование по английски

2024-06-26 11:45 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +    // Проверить кол-во объектов в классе
убрал ненужный метод

2024-06-26 11:46 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/TestUtils.java
> +                String key = getLastName(an.annotationType().getName());
нелюбимый вами метод getLastName наконец удалил

2024-06-26 11:57 UTC, GUlyanov commented on src/main/java/ru/innotech/annotations/Employee.java
> +    private BigDecimal fee;
Все исправлено

2024-06-27 11:01 UTC, Alexandr056 approved these changes
спасибо за проделанную работу, по прежнему названия переменных все из 2-3 букв, не ясно что мешает называть переменные так что бы это отражало их суть.
рекомендую так же использовать автоформатирование в студии(idea) для большей читабельности. 
папку ,idea добавить стоит в gitIgnore
Работу принимаю

2024-07-01 02:39 UTC, closed without merging